### ISSUE TITLE
Slack Invite link doesn't work

### ISSUE THREAD

**Issue by ebcarty** [nabla-containers/nabla-containers.github.io#30]
Currently links to:  https://slack.nabla-containers.com/  (doesn't resolve)
When trying out  https://nabla-containers.slack.com/  -- it asks for a login.

Please fix/update the invite link for Slack at your earliest convenience.

Thank you.

**Comment by lumjjb** [comment]
Thanks @ebcarty for pointing that out. In the meantime, can you try http://slack.nabla-containers.com/? (without https)

**Comment by lumjjb** [comment]
Should be resolved by https://github.com/nabla-containers/nabla-containers.github.io/commit/b14dc5939bd0cf7ab170fed42f3ed168743be067.

**Comment by ebcarty** [comment]
Fixed - thank you!
