### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ehirdoy** [nabla-containers/nabla-containers.github.io#31]
https://github.com/nabla-containers/nabla-containers.github.io/blame/master/_posts/2019-04-18-k8s-network-complications.md#L101

s/oddress/address/

**Comment by lumjjb** [comment]
Thanks for opening the issue! Hope you enjoy the blog posts!

**Comment by lumjjb** [comment]
Fixed!

**Comment by ehirdoy** [comment]
Sure I enjoyed a good article && I'm looking forward to the coming fs version too ;)
